### ISSUE TITLE
Is this package still in development?

### ISSUE THREAD

**Issue by dylanjm** [conao3/feather.el#1]
It's been my goal to leverage `leaf.el` in my init file, but I also want to move away from my dependency on `package.el`. I've been looking at using `straight.el` but figured I would look into the development of this package. Are there currently any other package managers that will work with `leaf.el`?

**Comment by conao3** [comment]
Now `leaf` supported as keyword: `package.el`, `el-get.el`, `straight.el`. Please see [leaf-keywords - ensure keywords](https://github.com/conao3/leaf-keywords.el#ensure-keywords)
I'm still dissatisfied with `package.el` and am willing to develop this package, but it's low priority. Would you like to develop together as a collaborator?

**Comment by conao3** [comment]
It works as a minimum and still lacks some features, but it has reached the standard of being able to register to MELPA.
PR is welcome!
