### ISSUE TITLE
Not starting after installation

### ISSUE THREAD

**Issue by berhoel** [conao3/feather.el#2]
After installing feather from MELPA and setting it up

```
use-package feather
  :ensure t
  :config
  (feather-mode))
```

I get an error message regarding a missing variable `ppp-minimum-warning-level--feather`. I was able to fix it by using:

```
use-package feather
  :ensure t
  :init
  (setq ppp-minimum-warning-level--feather 1)
  :config
  (feather-mode))
```

**Comment by conao3** [comment]
This issue is related to `ppp` bug and the bug is resolved at https://github.com/conao3/ppp.el/issues/57.

Please reinstall `ppp` and retry!

**Comment by berhoel** [comment]
Worked, thank you.
