### ISSUE TITLE
Question About Notice Part

### ISSUE THREAD

**Issue by yigitemres** [conao3/feather.el#8]
Hello there,

I'm using leaf for a very short time but I'm ❤️ it.  Because of this, I want to migrate from straight to feather in order to test feather but I have a problem. After installing feather like this:
```
(leaf feather
  :ensure t
  :config (feather-mode)
  )
```
can't install leaf-keywords like this:
```
(leaf leaf-keywords
  :feather t
  :config (leaf-keywords-init)
  )
```
But according to ReadMe/Notice part we can do like this:
```
(leaf leaf-keywordsq
  :feather t
  :config (leaf-keywords-init))
```
I'm probably missing something very simple and stupid but I cant find it 😢.

**Comment by conao3** [comment]
Thanks for interested in my packages!
Upon rereading, I found my documentation examples to be poor and hard to read.
I'd like to make improvements based on the discussion on this issue.

A quick way to try `feather` is to save the following init.el in `~/.debug.emacs.d/feather/init.el` and run it with `emacs -q -l ~/.debug.emacs.d/feather/init.el`.

The `feather` seems to work fine in my environment. How about this?

```emacs-lisp
;; ~/.debug.emacs.d/feather/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/{{pkg}}/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(eval-and-compile
  (customize-set-variable
   'package-archives '(("org" . "https://orgmode.org/elpa/")
                       ("melpa" . "https://melpa.org/packages/")
                       ("gnu" . "https://elpa.gnu.org/packages/")))
  (package-initialize)
  (unless (package-installed-p 'leaf)
    (package-refresh-contents)
    (package-install 'leaf))

  (leaf leaf-keywords
    :ensure t
    :init
    ;; optional packages if you want to use :hydra, :el-get, :blackout,,,
    (leaf feather
      :ensure t
      :custom ((leaf-alias-keyword-alist . '((:ensure . :feather))))
      :config (feather-mode))

    :config
    ;; initialize leaf-keywords.el
    (leaf-keywords-init)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; all my packages in MELPA

(leaf cort :ensure t)
(leaf ddskk-posframe :ensure t)
(leaf dired-git :ensure t)
(leaf dired-lsi :ensure t)
(leaf dired-posframe :ensure t)
(leaf feather :ensure t)
(leaf flycheck-indent :ensure t)
(leaf flycheck-keg :ensure t)
(leaf iceberg-theme :ensure t)
(leaf indent-lint :ensure t)
(leaf keg :ensure t)
(leaf keg-mode :ensure t)
(leaf leaf-manager :ensure t)
(leaf leaf-tree :ensure t)
(leaf oj :ensure t)
(leaf org-generate :ensure t)
(leaf ppp :ensure t)
(leaf scratch-comment :ensure t)
(leaf seml-mode :ensure t)
(leaf transient-dwim :ensure t)
```

![Screenshot_2020-08-18_01-52-18](https://user-images.githubusercontent.com/4703128/90422583-0e04e580-e0f6-11ea-95f3-c19caae7aee8.png)

**Comment by yigitemres** [comment]
Testing with magit but no luck. I'm using `GNU Emacs 27.1 (build 1, x86_64-w64-mingw32) of 2020-08-12` on Windows10.
![emacs_pf9I9pbmou](https://user-images.githubusercontent.com/3883354/90424468-db8fc400-e0c6-11ea-91c7-9131812a2bb2.png)

But I'm seeing all the packages on feather dashboard buffer.

**Comment by conao3** [comment]
It works for me. Arch linux, GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.21) of 2020-08-11
I don't know `feather` on Windows... What are you use Emacs on WSL? MSYS? official installer? or other?

```emacs-lisp
;; ~/.debug.emacs.d/feather/init.el

;; you can run like 'emacs -q -l ~/.debug.emacs.d/{{pkg}}/init.el'
(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(eval-and-compile
  (customize-set-variable
   'package-archives '(("org" . "https://orgmode.org/elpa/")
                       ("melpa" . "https://melpa.org/packages/")
                       ("gnu" . "https://elpa.gnu.org/packages/")))
  (package-initialize)
  (unless (package-installed-p 'leaf)
    (package-refresh-contents)
    (package-install 'leaf))

  (leaf leaf-keywords
    :ensure t
    :init
    ;; optional packages if you want to use :hydra, :el-get, :blackout,,,
    (leaf feather
      :ensure t
      :custom ((leaf-alias-keyword-alist . '((:ensure . :feather))))
      :config (feather-mode))

    :config
    ;; initialize leaf-keywords.el
    (leaf-keywords-init)))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; (leaf cort :ensure t)
;; (leaf ddskk-posframe :ensure t)
;; (leaf dired-git :ensure t)
;; (leaf dired-lsi :ensure t)
;; (leaf dired-posframe :ensure t)
;; (leaf feather :ensure t)
;; (leaf flycheck-indent :ensure t)
;; (leaf flycheck-keg :ensure t)
;; (leaf iceberg-theme :ensure t)
;; (leaf indent-lint :ensure t)
;; (leaf keg :ensure t)
;; (leaf keg-mode :ensure t)
;; (leaf leaf-manager :ensure t)
;; (leaf leaf-tree :ensure t)
;; (leaf oj :ensure t)
;; (leaf org-generate :ensure t)
;; (leaf ppp :ensure t)
;; (leaf scratch-comment :ensure t)
;; (leaf seml-mode :ensure t)
;; (leaf transient-dwim :ensure t)

(leaf magit :ensure t)
```
![Screenshot_2020-08-18_02-22-04](https://user-images.githubusercontent.com/4703128/90424762-9f298b80-e0f9-11ea-9781-e383b3b52476.png)

**Comment by yigitemres** [comment]
I'm using official GNU Emacs installer. BTW, I'm edited my last message but I'm gonna write here as well, I can see all the ensure keyworded packages on the \*feather dashboard\* but somehow they are not installed when I start emacs. May be this is normal behavior idk?

**Comment by conao3** [comment]
OK, Anyway, I don't have a Windows environment, so I can't test it.

I'm sorry, but I hope you can use `leaf` without `feather`.
I'm waiting for other Windows developers appear.

**Comment by yigitemres** [comment]
I'm test it in WSL Gentoo with your config and its working. I'm gonna migrating WSL Gentoo environment once WSL's own xserver comes with it. 
![WindowsTerminal_hXDXDHi508](https://user-images.githubusercontent.com/3883354/90427619-738fac80-e0cb-11ea-9b83-83c0e1b97dd4.png)

Thanks for you and all the contributors hard work on your every project. Have a nice day! 🥂
